In [20]:
import pandas as pd
from functools import reduce

# **variabel 1: AHH**

In [2]:
url1 = 'https://raw.githubusercontent.com/naiarch/faktor-analisis-dan-clustering-data-bps/main/Angka%20Harapan%20Hidup%20(AHH)%20Menurut%20Provinsi%20dan%20Jenis%20Kelamin%2C%202024.csv'
df1 = pd.read_csv(url1, skiprows=3, skipfooter=2, names=['Provinsi', 'Laki-laki', 'Perempuan'], engine='python')
df1

                Provinsi  Laki-laki  Perempuan
0                   ACEH      68.52      72.45
1         SUMATERA UTARA      68.36      72.30
2         SUMATERA BARAT      68.41      72.35
3                   RIAU      70.56      74.58
4                  JAMBI      70.09      74.09
5       SUMATERA SELATAN      69.00      72.95
6               BENGKULU      68.21      72.15
7                LAMPUNG      69.56      73.54
8   KEP. BANGKA BELITUNG      69.55      73.52
9              KEP. RIAU      69.30      73.27
10           DKI JAKARTA      72.08      76.28
11            JAWA BARAT      72.26      76.56
12           JAWA TENGAH      73.21      76.99
13         DI YOGYAKARTA      73.66      77.40
14            JAWA TIMUR      70.39      74.40
15                BANTEN      69.09      73.04
16                  BALI      71.19      75.49
17   NUSA TENGGARA BARAT      65.79      69.77
18   NUSA TENGGARA TIMUR      66.04      70.03
19      KALIMANTAN BARAT      69.61      73.59
20     KALIMANTAN TENGAH      68.51      72.44
21    KALIMANTAN SELATAN      67.72      71.67
22      KALIMANTAN TIMUR      73.21      76.90
23      KALIMANTAN UTARA      70.76      74.79
24        SULAWESI UTARA      70.73      74.76
25       SULAWESI TENGAH      67.49      71.44
26      SULAWESI SELATAN      69.49      73.47
27     SULAWESI TENGGARA      69.66      73.64
28             GORONTALO      67.16      71.12
29        SULAWESI BARAT      64.37      68.27
30                MALUKU      65.05      68.96
31          MALUKU UTARA      67.28      71.36
32           PAPUA BARAT      65.13      69.07
33      PAPUA BARAT DAYA      65.88      69.82
34                 PAPUA      66.76      70.79
35         PAPUA SELATAN      64.53      68.42
36          PAPUA TENGAH      65.05      68.97
37      PAPUA PEGUNUNGAN      62.83      66.68
38             INDONESIA      70.32      74.21

In [3]:
df1['AHH'] = (df1['Laki-laki'] + df1['Perempuan']) / 2

df1 = df1.drop(columns=['Laki-laki', 'Perempuan'])
df1 = df1.iloc[:38]
df1

                Provinsi     AHH
0                   ACEH  70.485
1         SUMATERA UTARA  70.330
2         SUMATERA BARAT  70.380
3                   RIAU  72.570
4                  JAMBI  72.090
5       SUMATERA SELATAN  70.975
6               BENGKULU  70.180
7                LAMPUNG  71.550
8   KEP. BANGKA BELITUNG  71.535
9              KEP. RIAU  71.285
10           DKI JAKARTA  74.180
11            JAWA BARAT  74.410
12           JAWA TENGAH  75.100
13         DI YOGYAKARTA  75.530
14            JAWA TIMUR  72.395
15                BANTEN  71.065
16                  BALI  73.340
17   NUSA TENGGARA BARAT  67.780
18   NUSA TENGGARA TIMUR  68.035
19      KALIMANTAN BARAT  71.600
20     KALIMANTAN TENGAH  70.475
21    KALIMANTAN SELATAN  69.695
22      KALIMANTAN TIMUR  75.055
23      KALIMANTAN UTARA  72.775
24        SULAWESI UTARA  72.745
25       SULAWESI TENGAH  69.465
26      SULAWESI SELATAN  71.480
27     SULAWESI TENGGARA  71.650
28             GORONTALO  69.140
29        SULAWESI BARAT  66.320
30                MALUKU  67.005
31          MALUKU UTARA  69.320
32           PAPUA BARAT  67.100
33      PAPUA BARAT DAYA  67.850
34                 PAPUA  68.775
35         PAPUA SELATAN  66.475
36          PAPUA TENGAH  67.010
37      PAPUA PEGUNUNGAN  64.755

# **variabel 2: sarana kesehatan**

In [4]:
url2 = 'https://raw.githubusercontent.com/naiarch/faktor-analisis-dan-clustering-data-bps/main/Jumlah%20Desa_Kelurahan%20Yang%20Memiliki%20Sarana%20Kesehatan%20Menurut%20Provinsi%2C%202024.csv'
df2 = pd.read_csv(url2)
df2

,Provinsi,Desa/Kelurahan Yang Memiliki Sarana Kesehatan - Rumah Sakit,Desa/Kelurahan Yang Memiliki Sarana Kesehatan - Rumah Sakit Bersalin,Desa/Kelurahan Yang Memiliki Sarana Kesehatan - Poliklinik,Desa/Kelurahan Yang Memiliki Sarana Kesehatan - Puskesmas,Desa/Kelurahan Yang Memiliki Sarana Kesehatan - Puskesmas Pembantu,Desa/Kelurahan Yang Memiliki Sarana Kesehatan - Apotek
0,Aceh,66.0,4,336.0,363.0,898.0,539.0
1,Sumatera Utara,176.0,10,844.0,624.0,1811.0,867.0
2,Sumatera Barat,64.0,7,169.0,280.0,713.0,370.0
3,Riau,66.0,1,302.0,244.0,996.0,478.0
4,Jambi,39.0,–,75.0,208.0,581.0,307.0
5,Sumatera Selatan,73.0,7,246.0,348.0,809.0,400.0
6,Bengkulu,24.0,–,60.0,181.0,388.0,210.0
7,Lampung,61.0,14,411.0,323.0,859.0,670.0
8,Kepulauan Bangka Belitung,23.0,3,54.0,66.0,147.0,134.0
9,Kepulauan Riau,26.0,3,71.0,96.0,225.0,97.0
10,DKI Jakarta,121.0,22,236.0,52.0,234.0,255.0
11,Jawa Barat,346.0,42,1923.0,1110.0,1547.0,2589.0
12,Jawa Tengah,317.0,–,1295.0,888.0,1697.0,2903.0
13,DI Yogyakarta,66.0,1,158.0,122.0,229.0,254.0
14,Jawa Timur,341.0,65,1327.0,984.0,2218.0,2628.0
15,Banten,106.0,6,537.0,252.0,220.0,526.0
16,Bali,59.0,4,141.0,120.0,480.0,308.0
17,Nusa Tenggara Barat,42.0,–,103.0,178.0,550.0,433.0
18,Nusa Tenggara Timur,65.0,–,119.0,442.0,1050.0,296.0
19,Kalimantan Barat,45.0,5,106.0,248.0,776.0,222.0
20,Kalimantan Tengah,27.0,1,96.0,211.0,1096.0,137.0
21,Kalimantan Selatan,42.0,–,137.0,243.0,406.0,266.0
22,Kalimantan Timur,46.0,2,161.0,185.0,741.0,269.0
23,Kalimantan Utara,15.0,–,26.0,60.0,221.0,68.0
24,Sulawesi Utara,54.0,2,64.0,208.0,420.0,258.0
25,Sulawesi Tengah,36.0,5,60.0,221.0,659.0,316.0
26,Sulawesi Selatan,101.0,22,239.0,475.0,1324.0,794.0
27,Sulawesi Tenggara,33.0,3,46.0,309.0,417.0,344.0
28,Gorontalo,19.0,1,79.0,95.0,211.0,117.0
29,Sulawesi Barat,12.0,–,18.0,100.0,344.0,98.0
30,Maluku,31.0,–,35.0,237.0,463.0,93.0
31,Maluku Utara,23.0,–,21.0,153.0,287.0,121.0
32,Papua Barat,11.0,–,13.0,91.0,214.0,53.0
33,Papua Barat Daya,12.0,–,15.0,104.0,202.0,58.0
34,Papua,17.0,–,21.0,125.0,310.0,79.0
35,Papua Selatan,9.0,–,16.0,88.0,246.0,26.0
36,Papua Tengah,14.0,–,24.0,98.0,148.0,45.0
37,Papua Pegunungan,9.0,–,12.0,148.0,246.0,8.0
38,Indonesia,2637.0,230,9596.0,10280.0,24383.0,17636.0
39,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,Catatan,NaN,NaN,NaN,NaN,NaN,NaN
41,1Desa pada tabel ini termasuk Unit Permukiman ...,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df2 = df2[[
    'Provinsi',
    'Desa/Kelurahan Yang Memiliki Sarana Kesehatan - Rumah Sakit',
    'Desa/Kelurahan Yang Memiliki Sarana Kesehatan - Puskesmas'
]]

df2 = df2.iloc[:38]

df2

,Provinsi,Desa/Kelurahan Yang Memiliki Sarana Kesehatan - Rumah Sakit,Desa/Kelurahan Yang Memiliki Sarana Kesehatan - Puskesmas
0,Aceh,66.0,363.0
1,Sumatera Utara,176.0,624.0
2,Sumatera Barat,64.0,280.0
3,Riau,66.0,244.0
4,Jambi,39.0,208.0
5,Sumatera Selatan,73.0,348.0
6,Bengkulu,24.0,181.0
7,Lampung,61.0,323.0
8,Kepulauan Bangka Belitung,23.0,66.0
9,Kepulauan Riau,26.0,96.0
10,DKI Jakarta,121.0,52.0
11,Jawa Barat,346.0,1110.0
12,Jawa Tengah,317.0,888.0
13,DI Yogyakarta,66.0,122.0
14,Jawa Timur,341.0,984.0
15,Banten,106.0,252.0
16,Bali,59.0,120.0
17,Nusa Tenggara Barat,42.0,178.0
18,Nusa Tenggara Timur,65.0,442.0
19,Kalimantan Barat,45.0,248.0
20,Kalimantan Tengah,27.0,211.0
21,Kalimantan Selatan,42.0,243.0
22,Kalimantan Timur,46.0,185.0
23,Kalimantan Utara,15.0,60.0
24,Sulawesi Utara,54.0,208.0
25,Sulawesi Tengah,36.0,221.0
26,Sulawesi Selatan,101.0,475.0
27,Sulawesi Tenggara,33.0,309.0
28,Gorontalo,19.0,95.0
29,Sulawesi Barat,12.0,100.0
30,Maluku,31.0,237.0
31,Maluku Utara,23.0,153.0
32,Papua Barat,11.0,91.0
33,Papua Barat Daya,12.0,104.0
34,Papua,17.0,125.0
35,Papua Selatan,9.0,88.0
36,Papua Tengah,14.0,98.0
37,Papua Pegunungan,9.0,148.0

# **variabel 3: Persentase Penduduk Miskin**

In [6]:
url3 = 'https://raw.githubusercontent.com/naiarch/faktor-analisis-dan-clustering-data-bps/main/Jumlah%20dan%20Persentase%20Penduduk%20Miskin%20Menurut%20Provinsi%2C%202024.csv'
df3 = pd.read_csv(url3)
df3

,Provinsi,Garis Kemiskinan - Maret (Rp),Garis Kemiskinan - September (Rp),Jumlah Penduduk Miskin - Maret (ribu) (Ribu),Jumlah Penduduk Miskin - September (ribu) (Ribu),Persentase Penduduk Miskin - Maret,Persentase Penduduk Miskin - September
0,Aceh,661227,665855,804.53,718.96,14.23,12.64
1,Sumatera Utara,642423,648336,1228.01,1110.92,7.99,7.19
2,Sumatera Barat,708416,714991,345.73,315.43,5.97,5.42
3,Riau,697296,702620,492.25,473.04,6.67,6.36
4,Jambi,650115,658100,265.42,272.7,7.10,7.26
5,Sumatera Selatan,554197,564462,984.24,948.84,10.97,10.51
6,Bengkulu,671095,672816,281.36,261.15,13.56,12.52
7,Lampung,586551,599018,941.23,939.3,10.69,10.62
8,Kepulauan Bangka Belitung,908397,917673,69.95,78.58,4.55,5.08
9,Kepulauan Riau,787211,807602,138.30,124.96,5.37,4.78
10,DKI Jakarta,825288,846085,464.93,449.07,4.30,4.14
11,Jawa Barat,524052,535509,3848.67,3668.35,7.46,7.08
12,Jawa Tengah,507001,521093,3704.33,3396.34,10.47,9.58
13,DI Yogyakarta,602437,613370,445.55,430.47,10.83,10.40
14,Jawa Timur,536122,547751,3982.69,3893.82,9.79,9.56
15,Banten,654213,667403,791.61,777.49,5.84,5.70
16,Bali,568510,580306,184.43,176.21,4.00,3.80
17,Nusa Tenggara Barat,534703,540339,709.01,658.6,12.91,11.91
18,Nusa Tenggara Timur,527275,533944,1127.57,1107.94,19.48,19.02
19,Kalimantan Barat,595509,611320,336.08,333.99,6.32,6.25
20,Kalimantan Tengah,623954,641524,145.63,149.24,5.17,5.26
21,Kalimantan Selatan,632739,644107,183.31,180.2,4.11,4.02
22,Kalimantan Timur,833955,853997,221.34,211.88,5.78,5.51
23,Kalimantan Utara,854294,876375,47.83,41.11,6.32,5.38
24,Sulawesi Utara,490719,511710,186.86,173.3,7.25,6.70
25,Sulawesi Tengah,600872,608687,379.76,358.33,11.77,11.04
26,Sulawesi Selatan,459226,467991,736.48,711.77,8.06,7.77
27,Sulawesi Tenggara,462715,473343,319.71,305.27,11.21,10.63
28,Gorontalo,473006,487578,177.99,170.03,14.57,13.87
29,Sulawesi Barat,454879,460283,162.19,155.91,11.21,10.71
30,Maluku,713503,739818,297.68,293.99,16.05,15.78
31,Maluku Utara,604460,639337,83.09,79.69,6.32,6.03
32,Papua Barat,793804,816613,110.16,108.28,21.66,21.09
33,Papua Barat Daya,756237,791570,102.27,96.81,18.13,16.95
34,Papua,674371,708811,152.91,161.07,17.26,18.09
35,Papua Selatan,519979,...,92.20,...,17.44,19.35
36,Papua Tengah,764115,...,308.48,...,29.76,27.60
37,Papua Pegunungan,1007060,...,365.44,...,32.97,29.66
38,Indonesia,582932,595242,25219.20,24054.72,9.03,8.57

In [7]:
df3 = df3[['Provinsi','Persentase Penduduk Miskin - September']]
df3.columns = [
    'Provinsi',
    'Persentase_Penduduk_Miskin'
]
df3 = df3.iloc[:38]
df3

                     Provinsi  Persentase_Penduduk_Miskin
0                        Aceh                       12.64
1              Sumatera Utara                        7.19
2              Sumatera Barat                        5.42
3                        Riau                        6.36
4                       Jambi                        7.26
5            Sumatera Selatan                       10.51
6                    Bengkulu                       12.52
7                     Lampung                       10.62
8   Kepulauan Bangka Belitung                        5.08
9              Kepulauan Riau                        4.78
10                DKI Jakarta                        4.14
11                 Jawa Barat                        7.08
12                Jawa Tengah                        9.58
13              DI Yogyakarta                       10.40
14                 Jawa Timur                        9.56
15                     Banten                        5.70
16                       Bali                        3.80
17        Nusa Tenggara Barat                       11.91
18        Nusa Tenggara Timur                       19.02
19           Kalimantan Barat                        6.25
20          Kalimantan Tengah                        5.26
21         Kalimantan Selatan                        4.02
22           Kalimantan Timur                        5.51
23           Kalimantan Utara                        5.38
24             Sulawesi Utara                        6.70
25            Sulawesi Tengah                       11.04
26           Sulawesi Selatan                        7.77
27          Sulawesi Tenggara                       10.63
28                  Gorontalo                       13.87
29             Sulawesi Barat                       10.71
30                     Maluku                       15.78
31               Maluku Utara                        6.03
32                Papua Barat                       21.09
33           Papua Barat Daya                       16.95
34                      Papua                       18.09
35              Papua Selatan                       19.35
36               Papua Tengah                       27.60
37           Papua Pegunungan                       29.66

# **variabel 4: Kepadatan Penduduk**

In [8]:
url4 = 'https://raw.githubusercontent.com/naiarch/faktor-analisis-dan-clustering-data-bps/main/Penduduk%2C%20Laju%20Pertumbuhan%20Penduduk%2C%20Distribusi%20Persentase%20Penduduk%2C%20Kepadatan%20Penduduk%2C%20Rasio%20Jenis%20Kelamin%20Penduduk%20Menurut%20Provinsi%2C%202024.csv'
df4 = pd.read_csv(url4)
df4

,Provinsi,Jumlah Penduduk (Ribu),Laju Pertumbuhan Penduduk per Tahun,Persentase Penduduk,Kepadatan Penduduk per km persegi (Km2),Rasio Jenis Kelamin Penduduk
0,Aceh,5554.8,1.39,1.97,98.0,100.9
1,Sumatera Utara,15588.5,1.40,5.54,215.0,100.8
2,Sumatera Barat,5836.2,1.43,2.07,139.0,101.5
3,Riau,6728.1,1.37,2.39,75.0,104.4
4,Jambi,3724.3,1.30,1.32,76.0,103.4
5,Sumatera Selatan,8837.3,1.15,3.14,102.0,103.7
6,Bengkulu,2112.2,1.32,0.75,105.0,104.4
7,Lampung,9419.6,1.20,3.34,281.0,104.3
8,Kepulauan Bangka Belitung,1531.5,1.36,0.54,92.0,105.4
9,Kepulauan Riau,2183.3,1.50,0.78,264.0,103.3
10,DKI Jakarta,10684.9,0.31,3.79,16165.0,101.1
11,Jawa Barat,50345.2,1.13,17.88,1359.0,102.6
12,Jawa Tengah,37892.3,0.99,13.46,1104.0,101.0
13,DI Yogyakarta,3759.5,0.65,1.34,1186.0,97.9
14,Jawa Timur,41814.5,0.75,14.85,870.0,99.4
15,Banten,12431.4,1.16,4.41,1329.0,103.4
16,Bali,4433.3,0.71,1.57,793.0,100.5
17,Nusa Tenggara Barat,5646.0,1.60,2.00,287.0,100.7
18,Nusa Tenggara Timur,5656.0,1.62,2.01,122.0,100.0
19,Kalimantan Barat,5695.5,1.36,2.02,39.0,105.4
20,Kalimantan Tengah,2809.7,1.37,1.00,18.0,106.8
21,Kalimantan Selatan,4273.4,1.29,1.52,115.0,102.3
22,Kalimantan Timur,4045.9,1.93,1.44,32.0,107.3
23,Kalimantan Utara,739.8,1.41,0.26,11.0,110.7
24,Sulawesi Utara,2701.8,0.80,0.96,186.0,104.3
25,Sulawesi Tengah,3121.8,1.20,1.11,51.0,105.2
26,Sulawesi Selatan,9463.4,1.13,3.36,209.0,98.8
27,Sulawesi Tenggara,2793.1,1.67,0.99,77.0,102.6
28,Gorontalo,1227.8,1.26,0.44,102.0,101.7
29,Sulawesi Barat,1503.2,1.55,0.53,91.0,102.7
30,Maluku,1945.6,1.37,0.69,42.0,102.3
31,Maluku Utara,1355.6,1.48,0.48,41.0,105.1
32,Papua Barat,578.7,1.71,0.21,10.0,110.8
33,Papua Barat Daya,627.1,1.59,0.22,16.0,108.9
34,Papua,1060.6,1.36,0.38,13.0,109.7
35,Papua Selatan,542.1,1.45,0.19,5.0,108.0
36,Papua Tengah,1472.9,1.54,0.52,24.0,114.0
37,Papua Pegunungan,1467.0,1.43,0.52,29.0,114.5
38,Indonesia,281603.8,1.11,100.00,149.0,102.0
39,NaN,NaN,NaN,NaN,NaN,NaN
40,Catatan,NaN,NaN,NaN,NaN,NaN
41,<sup>1</sup> Hasil Proyeksi Penduduk Indonesia...,NaN,NaN,NaN,NaN,NaN
42,kabupaten/kota pembentuk/<i>The Population Gro...,NaN,NaN,NaN,NaN,NaN

In [9]:
df4 = df4[['Provinsi','Kepadatan Penduduk per km persegi (Km2)']]
df4.columns = [
    'Provinsi',
    'Kepadatan_Penduduk'
]

df4 = df4.iloc[:38]
df4

                     Provinsi  Kepadatan_Penduduk
0                        Aceh                98.0
1              Sumatera Utara               215.0
2              Sumatera Barat               139.0
3                        Riau                75.0
4                       Jambi                76.0
5            Sumatera Selatan               102.0
6                    Bengkulu               105.0
7                     Lampung               281.0
8   Kepulauan Bangka Belitung                92.0
9              Kepulauan Riau               264.0
10                DKI Jakarta             16165.0
11                 Jawa Barat              1359.0
12                Jawa Tengah              1104.0
13              DI Yogyakarta              1186.0
14                 Jawa Timur               870.0
15                     Banten              1329.0
16                       Bali               793.0
17        Nusa Tenggara Barat               287.0
18        Nusa Tenggara Timur               122.0
19           Kalimantan Barat                39.0
20          Kalimantan Tengah                18.0
21         Kalimantan Selatan               115.0
22           Kalimantan Timur                32.0
23           Kalimantan Utara                11.0
24             Sulawesi Utara               186.0
25            Sulawesi Tengah                51.0
26           Sulawesi Selatan               209.0
27          Sulawesi Tenggara                77.0
28                  Gorontalo               102.0
29             Sulawesi Barat                91.0
30                     Maluku                42.0
31               Maluku Utara                41.0
32                Papua Barat                10.0
33           Papua Barat Daya                16.0
34                      Papua                13.0
35              Papua Selatan                 5.0
36               Papua Tengah                24.0
37           Papua Pegunungan                29.0

# **variabel 5: Persentase Keluhan Kesehatan**

In [10]:
url5 = 'https://raw.githubusercontent.com/naiarch/faktor-analisis-dan-clustering-data-bps/main/Persentase%20Penduduk%20yang%20Mempunyai%20Keluhan%20Kesehatan%20dalam%20Sebulan%20Terakhir%20Menurut%20Provinsi%2C%202024.csv'
df5 = pd.read_csv(url5, skiprows=3, names=['Provinsi', 'Persentase Keluhan Kesehatan'])
df5

                Provinsi  Persentase Keluhan Kesehatan
0                   ACEH                         25.58
1         SUMATERA UTARA                         23.99
2         SUMATERA BARAT                         30.10
3                   RIAU                         23.60
4                  JAMBI                         23.73
5       SUMATERA SELATAN                         29.89
6               BENGKULU                         28.27
7                LAMPUNG                         29.54
8   KEP. BANGKA BELITUNG                         28.80
9              KEP. RIAU                         26.26
10           DKI JAKARTA                         24.07
11            JAWA BARAT                         28.88
12           JAWA TENGAH                         31.86
13         DI YOGYAKARTA                         28.82
14            JAWA TIMUR                         28.75
15                BANTEN                         25.77
16                  BALI                         19.32
17   NUSA TENGGARA BARAT                         38.88
18   NUSA TENGGARA TIMUR                         29.56
19      KALIMANTAN BARAT                         24.37
20     KALIMANTAN TENGAH                         21.37
21    KALIMANTAN SELATAN                         29.00
22      KALIMANTAN TIMUR                         20.01
23      KALIMANTAN UTARA                         19.93
24        SULAWESI UTARA                         23.30
25       SULAWESI TENGAH                         22.41
26      SULAWESI SELATAN                         23.43
27     SULAWESI TENGGARA                         20.87
28             GORONTALO                         33.80
29        SULAWESI BARAT                         23.33
30                MALUKU                         14.38
31          MALUKU UTARA                         13.22
32           PAPUA BARAT                         14.18
33      PAPUA BARAT DAYA                         17.43
34                 PAPUA                         14.43
35         PAPUA SELATAN                         21.24
36          PAPUA TENGAH                         10.72
37      PAPUA PEGUNUNGAN                          8.88
38             INDONESIA                         27.34

In [11]:
df5 = df5.iloc[:38]
df5

                Provinsi  Persentase Keluhan Kesehatan
0                   ACEH                         25.58
1         SUMATERA UTARA                         23.99
2         SUMATERA BARAT                         30.10
3                   RIAU                         23.60
4                  JAMBI                         23.73
5       SUMATERA SELATAN                         29.89
6               BENGKULU                         28.27
7                LAMPUNG                         29.54
8   KEP. BANGKA BELITUNG                         28.80
9              KEP. RIAU                         26.26
10           DKI JAKARTA                         24.07
11            JAWA BARAT                         28.88
12           JAWA TENGAH                         31.86
13         DI YOGYAKARTA                         28.82
14            JAWA TIMUR                         28.75
15                BANTEN                         25.77
16                  BALI                         19.32
17   NUSA TENGGARA BARAT                         38.88
18   NUSA TENGGARA TIMUR                         29.56
19      KALIMANTAN BARAT                         24.37
20     KALIMANTAN TENGAH                         21.37
21    KALIMANTAN SELATAN                         29.00
22      KALIMANTAN TIMUR                         20.01
23      KALIMANTAN UTARA                         19.93
24        SULAWESI UTARA                         23.30
25       SULAWESI TENGAH                         22.41
26      SULAWESI SELATAN                         23.43
27     SULAWESI TENGGARA                         20.87
28             GORONTALO                         33.80
29        SULAWESI BARAT                         23.33
30                MALUKU                         14.38
31          MALUKU UTARA                         13.22
32           PAPUA BARAT                         14.18
33      PAPUA BARAT DAYA                         17.43
34                 PAPUA                         14.43
35         PAPUA SELATAN                         21.24
36          PAPUA TENGAH                         10.72
37      PAPUA PEGUNUNGAN                          8.88

# **variabel 6: RLS**

In [12]:
url6 = 'https://raw.githubusercontent.com/naiarch/faktor-analisis-dan-clustering-data-bps/main/Rata-Rata%20Lama%20Sekolah%20Penduduk%20Umur%2015%20Tahun%20ke%20Atas%20Menurut%20Provinsi%2C%202024.csv'
df6 = pd.read_csv(url6, skiprows=3, names=['Provinsi', 'Rata-Rata Lama Sekolah'])
df6

                Provinsi  Rata-Rata Lama Sekolah
0                   ACEH                    9.95
1         SUMATERA UTARA                   10.18
2         SUMATERA BARAT                    9.72
3                   RIAU                    9.69
4                  JAMBI                    9.26
5       SUMATERA SELATAN                    8.98
6               BENGKULU                    9.40
7                LAMPUNG                    8.80
8   KEP. BANGKA BELITUNG                    8.78
9              KEP. RIAU                   10.65
10           DKI JAKARTA                   11.49
11            JAWA BARAT                    9.24
12           JAWA TENGAH                    8.47
13         DI YOGYAKARTA                   10.23
14            JAWA TIMUR                    8.69
15                BANTEN                    9.55
16                  BALI                    9.87
17   NUSA TENGGARA BARAT                    8.50
18   NUSA TENGGARA TIMUR                    8.48
19      KALIMANTAN BARAT                    8.28
20     KALIMANTAN TENGAH                    9.17
21    KALIMANTAN SELATAN                    9.02
22      KALIMANTAN TIMUR                   10.22
23      KALIMANTAN UTARA                    9.58
24        SULAWESI UTARA                   10.02
25       SULAWESI TENGAH                    9.28
26      SULAWESI SELATAN                    9.22
27     SULAWESI TENGGARA                    9.74
28             GORONTALO                    8.64
29        SULAWESI BARAT                    8.56
30                MALUKU                   10.44
31          MALUKU UTARA                    9.70
32           PAPUA BARAT                    9.87
33      PAPUA BARAT DAYA                   10.48
34                 PAPUA                   10.70
35         PAPUA SELATAN                    8.99
36          PAPUA TENGAH                    6.17
37      PAPUA PEGUNUNGAN                    5.10
38             INDONESIA                    9.22

In [13]:
df6.columns = [
    'Provinsi',
    'RLS'
]

df6 = df6.iloc[:38]
df6

                Provinsi    RLS
0                   ACEH   9.95
1         SUMATERA UTARA  10.18
2         SUMATERA BARAT   9.72
3                   RIAU   9.69
4                  JAMBI   9.26
5       SUMATERA SELATAN   8.98
6               BENGKULU   9.40
7                LAMPUNG   8.80
8   KEP. BANGKA BELITUNG   8.78
9              KEP. RIAU  10.65
10           DKI JAKARTA  11.49
11            JAWA BARAT   9.24
12           JAWA TENGAH   8.47
13         DI YOGYAKARTA  10.23
14            JAWA TIMUR   8.69
15                BANTEN   9.55
16                  BALI   9.87
17   NUSA TENGGARA BARAT   8.50
18   NUSA TENGGARA TIMUR   8.48
19      KALIMANTAN BARAT   8.28
20     KALIMANTAN TENGAH   9.17
21    KALIMANTAN SELATAN   9.02
22      KALIMANTAN TIMUR  10.22
23      KALIMANTAN UTARA   9.58
24        SULAWESI UTARA  10.02
25       SULAWESI TENGAH   9.28
26      SULAWESI SELATAN   9.22
27     SULAWESI TENGGARA   9.74
28             GORONTALO   8.64
29        SULAWESI BARAT   8.56
30                MALUKU  10.44
31          MALUKU UTARA   9.70
32           PAPUA BARAT   9.87
33      PAPUA BARAT DAYA  10.48
34                 PAPUA  10.70
35         PAPUA SELATAN   8.99
36          PAPUA TENGAH   6.17
37      PAPUA PEGUNUNGAN   5.10

# **variabel 7: TPT**

In [14]:
url7 = 'https://raw.githubusercontent.com/naiarch/faktor-analisis-dan-clustering-data-bps/main/Tingkat%20Pengangguran%20Terbuka%20Menurut%20Provinsi%20(Persen)%2C%202024.csv'
df7 = pd.read_csv(url7, skiprows=3, skipfooter=2, names=['Provinsi', 'Tingkat Pengangguran Terbuka'], engine='python')
df7

                Provinsi  Tingkat Pengangguran Terbuka
0                   ACEH                          5.75
1         SUMATERA UTARA                          5.60
2         SUMATERA BARAT                          5.75
3                   RIAU                          3.70
4                  JAMBI                          4.48
5       SUMATERA SELATAN                          3.86
6               BENGKULU                          3.11
7                LAMPUNG                          4.19
8   KEP. BANGKA BELITUNG                          4.63
9              KEP. RIAU                          6.39
10           DKI JAKARTA                          6.21
11            JAWA BARAT                          6.75
12           JAWA TENGAH                          4.78
13         DI YOGYAKARTA                          3.48
14            JAWA TIMUR                          4.19
15                BANTEN                          6.68
16                  BALI                          1.79
17   NUSA TENGGARA BARAT                          2.73
18   NUSA TENGGARA TIMUR                          3.02
19      KALIMANTAN BARAT                          4.86
20     KALIMANTAN TENGAH                          4.01
21    KALIMANTAN SELATAN                          4.20
22      KALIMANTAN TIMUR                          5.14
23      KALIMANTAN UTARA                          3.90
24        SULAWESI UTARA                          5.85
25       SULAWESI TENGAH                          2.94
26      SULAWESI SELATAN                          4.19
27     SULAWESI TENGGARA                          3.09
28             GORONTALO                          3.13
29        SULAWESI BARAT                          2.68
30                MALUKU                          6.11
31          MALUKU UTARA                          4.03
32           PAPUA BARAT                          4.13
33      PAPUA BARAT DAYA                          6.48
34                 PAPUA                          6.48
35         PAPUA SELATAN                          4.05
36          PAPUA TENGAH                          2.75
37      PAPUA PEGUNUNGAN                          1.32
38             INDONESIA                          4.91

In [15]:
df7.columns = [
    'Provinsi',
    'TPT'
]

df7 = df7.iloc[:38]
df7

                Provinsi   TPT
0                   ACEH  5.75
1         SUMATERA UTARA  5.60
2         SUMATERA BARAT  5.75
3                   RIAU  3.70
4                  JAMBI  4.48
5       SUMATERA SELATAN  3.86
6               BENGKULU  3.11
7                LAMPUNG  4.19
8   KEP. BANGKA BELITUNG  4.63
9              KEP. RIAU  6.39
10           DKI JAKARTA  6.21
11            JAWA BARAT  6.75
12           JAWA TENGAH  4.78
13         DI YOGYAKARTA  3.48
14            JAWA TIMUR  4.19
15                BANTEN  6.68
16                  BALI  1.79
17   NUSA TENGGARA BARAT  2.73
18   NUSA TENGGARA TIMUR  3.02
19      KALIMANTAN BARAT  4.86
20     KALIMANTAN TENGAH  4.01
21    KALIMANTAN SELATAN  4.20
22      KALIMANTAN TIMUR  5.14
23      KALIMANTAN UTARA  3.90
24        SULAWESI UTARA  5.85
25       SULAWESI TENGAH  2.94
26      SULAWESI SELATAN  4.19
27     SULAWESI TENGGARA  3.09
28             GORONTALO  3.13
29        SULAWESI BARAT  2.68
30                MALUKU  6.11
31          MALUKU UTARA  4.03
32           PAPUA BARAT  4.13
33      PAPUA BARAT DAYA  6.48
34                 PAPUA  6.48
35         PAPUA SELATAN  4.05
36          PAPUA TENGAH  2.75
37      PAPUA PEGUNUNGAN  1.32

# **variabel 8: HLS**

In [16]:
url8 = 'https://raw.githubusercontent.com/naiarch/faktor-analisis-dan-clustering-data-bps/main/%5BMetode%20Baru%5D%20Harapan%20Lama%20Sekolah%2C%202024.csv'
df8 = pd.read_csv(url8, skiprows=3, names=['Provinsi', 'Harapan Lama Sekolah'])
df8

               Provinsi Harapan Lama Sekolah
0                  ACEH                14.39
1              Simeulue                14.53
2          Aceh Singkil                14.36
3          Aceh Selatan                14.71
4         Aceh Tenggara                14.47
..                  ...                  ...
574    Mamberamo Tengah                 9.78
575              Yalimo                  9.8
576            Yahukimo                 8.05
577  Pegunungan Bintang                 7.01
578           INDONESIA                13.21

[579 rows x 2 columns]

In [17]:
provinsi = [
'ACEH','SUMATERA UTARA','SUMATERA BARAT','RIAU','JAMBI',
'SUMATERA SELATAN','BENGKULU','LAMPUNG',
'KEP. BANGKA BELITUNG','KEPULAUAN RIAU','DKI JAKARTA',
'JAWA BARAT','JAWA TENGAH','D I YOGYAKARTA',
'JAWA TIMUR','BANTEN','BALI',
'NUSA TENGGARA BARAT','NUSA TENGGARA TIMUR',
'KALIMANTAN BARAT','KALIMANTAN TENGAH',
'KALIMANTAN SELATAN','KALIMANTAN TIMUR',
'KALIMANTAN UTARA','SULAWESI UTARA',
'SULAWESI TENGAH','SULAWESI SELATAN',
'SULAWESI TENGGARA','GORONTALO',
'SULAWESI BARAT','MALUKU','MALUKU UTARA',
'PAPUA BARAT','PAPUA BARAT DAYA',
'PAPUA','PAPUA SELATAN',
'PAPUA TENGAH','PAPUA PEGUNUNGAN'
]

df8 = df8[df8['Provinsi'].isin(provinsi)]
df8.columns = [
    'Provinsi',
    'HLS'
]

df8 = df8.iloc[:38]
df8 = df8.reset_index(drop=True)

df8

                Provinsi    HLS
0                   ACEH  14.39
1         SUMATERA UTARA  13.49
2         SUMATERA BARAT   14.3
3                   RIAU  13.42
4                  JAMBI  13.14
5       SUMATERA SELATAN  12.64
6               BENGKULU  13.75
7                LAMPUNG  12.78
8   KEP. BANGKA BELITUNG  12.49
9         KEPULAUAN RIAU  13.27
10           DKI JAKARTA  13.51
11            JAWA BARAT   12.8
12           JAWA TENGAH  12.86
13        D I YOGYAKARTA   15.7
14            JAWA TIMUR  13.43
15                BANTEN   13.1
16                  BALI  13.62
17   NUSA TENGGARA BARAT  13.98
18   NUSA TENGGARA TIMUR  13.23
19      KALIMANTAN BARAT  12.68
20     KALIMANTAN TENGAH  12.77
21    KALIMANTAN SELATAN  12.87
22      KALIMANTAN TIMUR  14.03
23      KALIMANTAN UTARA  13.21
24        SULAWESI UTARA  12.97
25       SULAWESI TENGAH  13.34
26      SULAWESI SELATAN  13.55
27     SULAWESI TENGGARA  13.71
28             GORONTALO  13.17
29        SULAWESI BARAT  12.89
30                MALUKU  14.09
31          MALUKU UTARA  13.75
32           PAPUA BARAT  13.17
33      PAPUA BARAT DAYA  13.88
34                 PAPUA  13.72
35         PAPUA SELATAN  12.67
36          PAPUA TENGAH   9.63
37      PAPUA PEGUNUNGAN   9.97

In [22]:
import pandas as pd

# @title menyamakan nama provinsi

def clean_province(df):

    df['Provinsi'] = (
        df['Provinsi']
        .str.upper()
        .str.strip()
    )

    df['Provinsi'] = df['Provinsi'].replace({
        'KEPULAUAN RIAU':'KEP. RIAU',
        'KEPULAUAN BANGKA BELITUNG':'KEP. BANGKA BELITUNG',
        'D I YOGYAKARTA':'DI YOGYAKARTA'
    })

    return df

In [23]:
for df in [df1,df2,df3,df4,df5,df6,df7,df8]:
    clean_province(df)

/tmp/ipykernel_63812/1462977985.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Provinsi'] = (
/tmp/ipykernel_63812/1462977985.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Provinsi'] = df['Provinsi'].replace({

# **MERGE DATA**

In [24]:
dfs = [df1,df2,df3,df4,df5,df6,df7,df8]

df_final = reduce(
    lambda left,right:
    pd.merge(
        left,
        right,
        on='Provinsi',
        how='inner'
    ),
    dfs
)

df_final

,Provinsi,AHH,Desa/Kelurahan Yang Memiliki Sarana Kesehatan - Rumah Sakit,Desa/Kelurahan Yang Memiliki Sarana Kesehatan - Puskesmas,Persentase_Penduduk_Miskin,Kepadatan_Penduduk,Persentase Keluhan Kesehatan,RLS,TPT,HLS
0,ACEH,70.485,66.0,363.0,12.64,98.0,25.58,9.95,5.75,14.39
1,SUMATERA UTARA,70.330,176.0,624.0,7.19,215.0,23.99,10.18,5.60,13.49
2,SUMATERA BARAT,70.380,64.0,280.0,5.42,139.0,30.10,9.72,5.75,14.3
3,RIAU,72.570,66.0,244.0,6.36,75.0,23.60,9.69,3.70,13.42
4,JAMBI,72.090,39.0,208.0,7.26,76.0,23.73,9.26,4.48,13.14
5,SUMATERA SELATAN,70.975,73.0,348.0,10.51,102.0,29.89,8.98,3.86,12.64
6,BENGKULU,70.180,24.0,181.0,12.52,105.0,28.27,9.40,3.11,13.75
7,LAMPUNG,71.550,61.0,323.0,10.62,281.0,29.54,8.80,4.19,12.78
8,KEP. BANGKA BELITUNG,71.535,23.0,66.0,5.08,92.0,28.80,8.78,4.63,12.49
9,KEP. RIAU,71.285,26.0,96.0,4.78,264.0,26.26,10.65,6.39,13.27
10,DKI JAKARTA,74.180,121.0,52.0,4.14,16165.0,24.07,11.49,6.21,13.51
11,JAWA BARAT,74.410,346.0,1110.0,7.08,1359.0,28.88,9.24,6.75,12.8
12,JAWA TENGAH,75.100,317.0,888.0,9.58,1104.0,31.86,8.47,4.78,12.86
13,DI YOGYAKARTA,75.530,66.0,122.0,10.40,1186.0,28.82,10.23,3.48,15.7
14,JAWA TIMUR,72.395,341.0,984.0,9.56,870.0,28.75,8.69,4.19,13.43
15,BANTEN,71.065,106.0,252.0,5.70,1329.0,25.77,9.55,6.68,13.1
16,BALI,73.340,59.0,120.0,3.80,793.0,19.32,9.87,1.79,13.62
17,NUSA TENGGARA BARAT,67.780,42.0,178.0,11.91,287.0,38.88,8.50,2.73,13.98
18,NUSA TENGGARA TIMUR,68.035,65.0,442.0,19.02,122.0,29.56,8.48,3.02,13.23
19,KALIMANTAN BARAT,71.600,45.0,248.0,6.25,39.0,24.37,8.28,4.86,12.68
20,KALIMANTAN TENGAH,70.475,27.0,211.0,5.26,18.0,21.37,9.17,4.01,12.77
21,KALIMANTAN SELATAN,69.695,42.0,243.0,4.02,115.0,29.00,9.02,4.20,12.87
22,KALIMANTAN TIMUR,75.055,46.0,185.0,5.51,32.0,20.01,10.22,5.14,14.03
23,KALIMANTAN UTARA,72.775,15.0,60.0,5.38,11.0,19.93,9.58,3.90,13.21
24,SULAWESI UTARA,72.745,54.0,208.0,6.70,186.0,23.30,10.02,5.85,12.97
25,SULAWESI TENGAH,69.465,36.0,221.0,11.04,51.0,22.41,9.28,2.94,13.34
26,SULAWESI SELATAN,71.480,101.0,475.0,7.77,209.0,23.43,9.22,4.19,13.55
27,SULAWESI TENGGARA,71.650,33.0,309.0,10.63,77.0,20.87,9.74,3.09,13.71
28,GORONTALO,69.140,19.0,95.0,13.87,102.0,33.80,8.64,3.13,13.17
29,SULAWESI BARAT,66.320,12.0,100.0,10.71,91.0,23.33,8.56,2.68,12.89
30,MALUKU,67.005,31.0,237.0,15.78,42.0,14.38,10.44,6.11,14.09
31,MALUKU UTARA,69.320,23.0,153.0,6.03,41.0,13.22,9.70,4.03,13.75
32,PAPUA BARAT,67.100,11.0,91.0,21.09,10.0,14.18,9.87,4.13,13.17
33,PAPUA BARAT DAYA,67.850,12.0,104.0,16.95,16.0,17.43,10.48,6.48,13.88
34,PAPUA,68.775,17.0,125.0,18.09,13.0,14.43,10.70,6.48,13.72
35,PAPUA SELATAN,66.475,9.0,88.0,19.35,5.0,21.24,8.99,4.05,12.67
36,PAPUA TENGAH,67.010,14.0,98.0,27.60,24.0,10.72,6.17,2.75,9.63
37,PAPUA PEGUNUNGAN,64.755,9.0,148.0,29.66,29.0,8.88,5.10,1.32,9.97

In [25]:
# @title missing value
df_final.isnull().sum()

Provinsi                                                       0
AHH                                                            0
Desa/Kelurahan Yang Memiliki Sarana Kesehatan - Rumah Sakit    0
Desa/Kelurahan Yang Memiliki Sarana Kesehatan - Puskesmas      0
Persentase_Penduduk_Miskin                                     0
Kepadatan_Penduduk                                             0
Persentase Keluhan Kesehatan                                   0
RLS                                                            0
TPT                                                            0
HLS                                                            0
dtype: int64

In [26]:
# @title cek duplikasi data

df_final.duplicated().sum()

np.int64(0)

# **DATASET FINAL**

In [27]:
df_final.to_csv(
    'dataset_paper_statmul.csv',
    index=False
)